DROP TABLE IF EXISTS countries;
CREATE TABLE IF NOT EXISTS countries(
   id_country INTEGER  NOT NULL PRIMARY KEY 
  ,name       VARCHAR(20) NOT NULL
);
INSERT INTO countries(id_country,name) VALUES (0,'France');
INSERT INTO countries(id_country,name) VALUES (1,'Belgium');
INSERT INTO countries(id_country,name) VALUES (2,'United States');
INSERT INTO countries(id_country,name) VALUES (3,'Uruguay');
INSERT INTO countries(id_country,name) VALUES (4,'Thailand');
INSERT INTO countries(id_country,name) VALUES (5,'China');
INSERT INTO countries(id_country,name) VALUES (6,'Canada');
INSERT INTO countries(id_country,name) VALUES (7,'United Kingdom');
INSERT INTO countries(id_country,name) VALUES (8,'India');
INSERT INTO countries(id_country,name) VALUES (9,'Pakistan');
INSERT INTO countries(id_country,name) VALUES (10,'South Korea');
INSERT INTO countries(id_country,name) VALUES (11,'Denmark');
INSERT INTO countries(id_country,name) VALUES (12,'Turkey');
INSERT INTO countries(id_country,name) VALUES (13,'Brazil');
INSERT INTO countries(id_country,name) VALUES (14,'Italy');
INSERT INTO countries(id_country,name) VALUES (15,'Netherlands');
INSERT INTO countries(id_country,name) VALUES (16,'Indonesia');
INSERT INTO countries(id_country,name) VALUES (17,'Spain');
INSERT INTO countries(id_country,name) VALUES (18,'Ireland');
INSERT INTO countries(id_country,name) VALUES (19,'Hong Kong');
INSERT INTO countries(id_country,name) VALUES (20,'Morocco');
INSERT INTO countries(id_country,name) VALUES (21,'Mexico');
INSERT INTO countries(id_country,name) VALUES (22,'Vietnam');
INSERT INTO countries(id_country,name) VALUES (23,'Argentina');
INSERT INTO countries(id_country,name) VALUES (24,'Nigeria');
INSERT INTO countries(id_country,name) VALUES (25,'Japan');
INSERT INTO countries(id_country,name) VALUES (26,'Germany');
INSERT INTO countries(id_country,name) VALUES (27,'Greece');
INSERT INTO countries(id_country,name) VALUES (28,'Norway');
INSERT INTO countries(id_country,name) VALUES (29,'Switzerland');
INSERT INTO countries(id_country,name) VALUES (30,'United Arab Emirates');
INSERT INTO countries(id_country,name) VALUES (31,'Lebanon');
INSERT INTO countries(id_country,name) VALUES (32,'Cambodia');
INSERT INTO countries(id_country,name) VALUES (33,'Russia');
INSERT INTO countries(id_country,name) VALUES (34,'Poland');
INSERT INTO countries(id_country,name) VALUES (35,'Israel');
INSERT INTO countries(id_country,name) VALUES (36,'Australia');
INSERT INTO countries(id_country,name) VALUES (37,'Portugal');
INSERT INTO countries(id_country,name) VALUES (38,'Sweden');
INSERT INTO countries(id_country,name) VALUES (39,'Egypt');
INSERT INTO countries(id_country,name) VALUES (40,'Taiwan');
INSERT INTO countries(id_country,name) VALUES (41,'Austria');
INSERT INTO countries(id_country,name) VALUES (42,'Czech Republic');
INSERT INTO countries(id_country,name) VALUES (43,'Senegal');
INSERT INTO countries(id_country,name) VALUES (44,'Soviet Union');
INSERT INTO countries(id_country,name) VALUES (45,'Peru');
INSERT INTO countries(id_country,name) VALUES (46,'Ukraine');
INSERT INTO countries(id_country,name) VALUES (47,'Malaysia');
INSERT INTO countries(id_country,name) VALUES (48,'South Africa');
INSERT INTO countries(id_country,name) VALUES (49,'Nepal');
INSERT INTO countries(id_country,name) VALUES (50,'Philippines');
INSERT INTO countries(id_country,name) VALUES (51,'Serbia');
INSERT INTO countries(id_country,name) VALUES (52,'Colombia');
INSERT INTO countries(id_country,name) VALUES (53,'Singapore');
INSERT INTO countries(id_country,name) VALUES (54,'Luxembourg');
INSERT INTO countries(id_country,name) VALUES (55,'Bulgaria');
INSERT INTO countries(id_country,name) VALUES (56,'West Germany');
INSERT INTO countries(id_country,name) VALUES (57,'Cayman Islands');
INSERT INTO countries(id_country,name) VALUES (58,'New Zealand');
INSERT INTO countries(id_country,name) VALUES (59,'Venezuela');
INSERT INTO countries(id_country,name) VALUES (60,'Jordan');
INSERT INTO countries(id_country,name) VALUES (61,'Saudi Arabia');
INSERT INTO countries(id_country,name) VALUES (62,'Iceland');
INSERT INTO countries(id_country,name) VALUES (63,'Malta');
INSERT INTO countries(id_country,name) VALUES (64,'Qatar');
INSERT INTO countries(id_country,name) VALUES (65,'Chile');
INSERT INTO countries(id_country,name) VALUES (66,'Iran');
INSERT INTO countries(id_country,name) VALUES (67,'Finland');
INSERT INTO countries(id_country,name) VALUES (68,'Iraq');
INSERT INTO countries(id_country,name) VALUES (69,'Liechtenstein');
INSERT INTO countries(id_country,name) VALUES (70,'Albania');
INSERT INTO countries(id_country,name) VALUES (71,'Slovakia');
INSERT INTO countries(id_country,name) VALUES (72,'Samoa');
INSERT INTO countries(id_country,name) VALUES (73,'Ghana');
INSERT INTO countries(id_country,name) VALUES (74,'Botswana');
INSERT INTO countries(id_country,name) VALUES (75,'Hungary');
INSERT INTO countries(id_country,name) VALUES (76,'Guatemala');
INSERT INTO countries(id_country,name) VALUES (77,'Malawi');
INSERT INTO countries(id_country,name) VALUES (78,'Paraguay');
INSERT INTO countries(id_country,name) VALUES (79,'Somalia');
INSERT INTO countries(id_country,name) VALUES (80,'Kenya');
INSERT INTO countries(id_country,name) VALUES (81,'Sudan');
INSERT INTO countries(id_country,name) VALUES (82,'Sri Lanka');
INSERT INTO countries(id_country,name) VALUES (83,'Dominican Republic');
INSERT INTO countries(id_country,name) VALUES (84,'Panama');
INSERT INTO countries(id_country,name) VALUES (85,'Romania');
INSERT INTO countries(id_country,name) VALUES (86,'Latvia');
INSERT INTO countries(id_country,name) VALUES (87,'Uganda');
INSERT INTO countries(id_country,name) VALUES (88,'Slovenia');
INSERT INTO countries(id_country,name) VALUES (89,'Croatia');
INSERT INTO countries(id_country,name) VALUES (90,'Montenegro');
INSERT INTO countries(id_country,name) VALUES (91,'Bangladesh');
INSERT INTO countries(id_country,name) VALUES (92,'Vatican City');
INSERT INTO countries(id_country,name) VALUES (93,'East Germany');
INSERT INTO countries(id_country,name) VALUES (94,'Afghanistan');
INSERT INTO countries(id_country,name) VALUES (95,'Georgia');
INSERT INTO countries(id_country,name) VALUES (96,'Namibia');
INSERT INTO countries(id_country,name) VALUES (97,'Zimbabwe');
INSERT INTO countries(id_country,name) VALUES (98,'Cuba');
INSERT INTO countries(id_country,name) VALUES (99,'Azerbaijan');
INSERT INTO countries(id_country,name) VALUES (100,'Mauritius');
INSERT INTO countries(id_country,name) VALUES (101,'Nicaragua');
INSERT INTO countries(id_country,name) VALUES (102,'Kazakhstan');
INSERT INTO countries(id_country,name) VALUES (103,'Armenia');
INSERT INTO countries(id_country,name) VALUES (104,'Mongolia');
INSERT INTO countries(id_country,name) VALUES (105,'Bermuda');
INSERT INTO countries(id_country,name) VALUES (106,'Ecuador');
INSERT INTO countries(id_country,name) VALUES (107,'Syria');
INSERT INTO countries(id_country,name) VALUES (108,'Kuwait');
INSERT INTO countries(id_country,name) VALUES (109,'Cyprus');
